# Site settings
title: Megara Soluciones
email:
description: ""
baseurl: ""
url: "http://megara.com.ve"

twitter_username:
github_username: https://github.com/megara-ve

# Build settings
markdown: kramdown
